routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\KpiController;
use App\Http\Controllers\OutletController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RencanaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Dashboard
Route::middleware(['auth:sanctum', 'checkRole:Admin,SPV,CSO'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('/');
    Route::resource('dashboard', DashboardController::class);
});

// Rencana Buat Routes
Route::middleware(['auth', 'checkRole:Admin,SPV'])->group(function () {
    Route::get('/buat-rencana', [RencanaController::class, 'create'])->name('rencana.create');
    Route::post('/rencana/store', [RencanaController::class, 'store'])->name('rencana.store');
    Route::delete('/rencana/delete/{id}', [RencanaController::class, 'destroy'])->name('rencana.delete');
    Route::put('/rencana/edit/{id}', [RencanaController::class, 'update'])->name('rencana.update');
});

// Rencana Routes
Route::middleware(['auth', 'checkRole:Admin,SPV,CSO'])->group(function () {
    Route::get('/rencana-aktif', [RencanaController::class, 'index'])->name('rencana.index');
    Route::get('/rencana-selesai', [RencanaController::class, 'selesai'])->name('rencana.selesai');
    Route::put('/rencana/done/{id}', [RencanaController::class, 'done'])->name('rencana.done');
});

// Kpi Routes
Route::middleware(['auth', 'checkRole:Admin,SPV,CSO'])->group(function () {
    Route::resource('kpi-data', KpiController::class);
    Route::delete('/kpi-data/delete/{id}', [KpiController::class, 'destroy'])->name('kpi-data.delete');
    Route::get('/kpi-msa', [KpiController::class, 'msa'])->name('kpi-data.msa');
    Route::get('/kpi-omb', [KpiController::class, 'omb'])->name('kpi-data.omb');
    Route::get('/kpi-qsso', [KpiController::class, 'qsso'])->name('kpi-data.qsso');
    Route::get('/kpi-quro', [KpiController::class, 'quro'])->name('kpi-data.quro');
    Route::get('/kpi-sc', [KpiController::class, 'sc'])->name('kpi-data.sc');
    Route::get('/kpi-ssohvc', [KpiController::class, 'ssohvc'])->name('kpi-data.ssohvc');
    Route::get('/kpi-sqsso', [KpiController::class, 'sqsso'])->name('kpi-data.sqsso');
    Route::get('/kpi-ssc', [KpiController::class, 'ssc'])->name('kpi-data.ssc');
});

// Site Routes
Route::middleware(['auth', 'checkRole:Admin,SPV,CSO'])->group(function () {
    Route::resource('site-data', SiteController::class);
    Route::put('/site-data/edit/{id}', [SiteController::class, 'update'])->name('site-data.edit');
    Route::delete('/site-data/delete/{id}', [SiteController::class, 'destroy'])->name('site-data.delete');
    Route::get('/site-transaction', [SiteController::class, 'siteTransaction'])->name('site-data.siteTransaction');
});

// Outlet Routes
Route::middleware(['auth', 'checkRole:Admin,SPV,CSO'])->group(function () {
    Route::resource('outlet-data', OutletController::class);
    Route::put('/outlet-data/edit/{id}', [OutletController::class, 'update'])->name('outlet-data.edit');
    Route::get('/outlet-transaction', [OutletController::class, 'OutletTransaction'])->name('outlet-data.outletTransaction');
    Route::delete('/outlet-data/delete/{id}', [OutletController::class, 'destroy'])->name('outlet-data.delete');
});

// Import Routes
Route::middleware(['auth', 'checkRole:Admin,SPV'])->group(function () {
    Route::resource('import', ImportController::class);
    Route::post('import-kpi-outlet', [ImportController::class, 'importKpiOutlet'])->name('import-kpi-outlet');
    Route::post('import-site', [ImportController::class, 'importSite'])->name('import-site');
});

// User Routes
Route::middleware(['auth', 'checkRole:Admin'])->group(function () {
    Route::resource('user', UserController::class);
});

// Profile
Route::put('editProfile/{id}', [UserController::class, 'update'])->name('editProfile');
Route::put('editPassword/{id}', [UserController::class, 'changePassword'])->name('editPassword');

resources/views/includes/admin/footer.blade.php
<div class="page-footer">
    <div class="row">
        <div class="col-md-12">
            <span class="footer-text">2021 © Indosat Ooredoo Makassar</span>
        </div>
    </div>
</div>

resources/views/includes/admin/horizontal-bar.blade.php
<?php 
    $user = $user = Auth::user();
?>
<div class="horizontal-bar">
    <div class="logo-box"><a href="#" class="logo-text">monitoring</a></div>
    <a href="#" class="hide-horizontal-bar"><i class="material-icons">close</i></a>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="horizontal-bar-menu">
                    <ul>
                        @if($user->role !== 'Admin' && $user->role !== 'SPV')
                        <li class="{{ (request()->routeIs('dashboard.*')) || (request()->routeIs('/')) ? 'active-page' : '' }}">
                            <a href="{{ route('dashboard.index') }}"><i class="material-icons-outlined">dashboard</i> Dashboard</a>
                        </li>
                        @endif
                        <li class="{{ (request()->routeIs('rencana.*')) ? 'active-page' : '' }}">
                            <a href=""><i class="material-icons-outlined">assignment</i> Rencana<i class="material-icons">keyboard_arrow_down</i></a>
                            <ul class="sub-menu">
                                @if($user->role !== 'CSO')
                                <li>
                                    <a href="{{ route('rencana.create') }}" class="{{ (request()->routeIs('rencana.create')) ? 'active' : '' }}">Buat Rencana</a>
                                </li>
                                @endif
                                <li>
                                    <a href="{{ route('rencana.index') }}" class="{{ (request()->routeIs('rencana.index')) ? 'active' : '' }}">Rencana Aktif</a>
                                </li>
                                <li>
                                    <a href="{{ route('rencana.selesai') }}" class="{{ (request()->routeIs('rencana.selesai')) ? 'active' : '' }}">Rencana Selesai</a>
                                </li>
                            </ul>
                        </li>
                        <li class="{{ (request()->routeIs('site-data.*')) || (request()->routeIs('site-transaction.*')) ? 'active-page' : '' }}">
                            <a href=""><i class="material-icons-outlined">settings_input_antenna</i> Site<i class="material-icons">keyboard_arrow_down</i></a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="{{ route('site-data.index') }}" class="{{ (request()->routeIs('site-data.index')) ? 'active' : '' }}">Data Site</a>
                                </li>
                                <li>
                                    <a href="/site-transaction" class="{{ (request()->routeIs('site-data.siteTransaction')) ? 'active' : '' }}">Transaksi Site</a>
                                </li>
                            </ul>
                        </li>
                        <li class="{{ (request()->routeIs('outlet-data.*')) ? 'active-page' : '' }}">
                            <a href=""><i class="material-icons-outlined">store</i> Outlet<i class="material-icons">keyboard_arrow_down</i></a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="{{ route('outlet-data.index') }}" class="{{ (request()->routeIs('outlet-data.index')) ? 'active' : '' }}">Data Outlet</a>
                                </li>
                                <li>
                                    <a href="/outlet-transaction" class="{{ (request()->routeIs('outlet-data.outletTransaction')) ? 'active' : '' }}">Transaksi Outlet</a>
                                </li>
                            </ul>
                        </li>
                        <li class="{{ (request()->routeIs('kpi-data.*')) ? 'active-page' : '' }}">
                            <a href=""><i class="material-icons-outlined">show_chart</i> KPI CSO<i class="material-icons">keyboard_arrow_down</i></a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="{{ route('kpi-data.index') }}" class="{{ (request()->routeIs('kpi-data.index')) ? 'active' : '' }}">Score</a>
                                </li>
                                <li>
                                    <a href="/kpi-msa" class="{{ (request()->routeIs('kpi-data.msa')) ? 'active' : '' }}">MSA</a>
                                </li>
                                <li>
                                    <a href="/kpi-omb" class="{{ (request()->routeIs('kpi-data.omb')) ? 'active' : '' }}">OMB</a>
                                </li>
                                <li>
                                    <a href="/kpi-qsso" class="{{ (request()->routeIs('kpi-data.qsso')) ? 'active' : '' }}">QSSO</a>
                                </li>
                                <li>
                                    <a href="/kpi-quro" class="{{ (request()->routeIs('kpi-data.quro')) ? 'active' : '' }}">QURO</a>
                                </li>
                                <li>
                                    <a href="/kpi-sc" class="{{ (request()->routeIs('kpi-data.sc')) ? 'active' : '' }}">Serious Customer</a>
                                </li>
                                <li>
                                    <a href="/kpi-ssohvc" class="{{ (request()->routeIs('kpi-data.ssohvc')) ? 'active' : '' }}">SSO HVC</a>
                                </li>
                                <li>
                                    <a href="/kpi-sqsso" class="{{ (request()->routeIs('kpi-data.sqsso')) ? 'active' : '' }}">Serious QSSO</a>
                                </li>
                                <li>
                                    <a href="/kpi-ssc" class="{{ (request()->routeIs('kpi-data.ssc')) ? 'active' : '' }}">Site Serious Customer</a>
                                </li>
                            </ul>
                        </li>
                        @if($user->role == 'Admin' || $user->role == 'SPV')
                        <li class="{{ (request()->routeIs('import.*')) ? 'active-page' : '' }}">
                            <a href="{{ route('import.index') }}"><i class="material-icons-outlined">cloud_upload</i> Import Data</a>
                        </li>
                        @endif
                        @if($user->role == 'Admin')
                        <li class="{{ (request()->routeIs('user.*')) ? 'active-page' : '' }}">
                            <a href="{{ route('user.index') }}"><i class="material-icons-outlined">account_circle</i> User</a>
                        </li>
                        @endif
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/includes/admin/navbar.blade.php
<?php 
    $current_user = auth()->user();
?>
<div class="page-header">
    <nav class="navbar navbar-expand container">
        <ul class="navbar-nav">
            <li class="nav-item small-screens-sidebar-link">
                <a href="#" class="nav-link"><i class="material-icons-outlined">menu</i></a>
            </li>
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="{{asset('admin/images/avatars/profile-image-2.png')}}" alt="profile image">
                    <span>{{auth()->user()->name}}</span><i class="material-icons dropdown-icon">keyboard_arrow_down</i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#editProfile{{$current_user->id}}">Profil</a>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#editPassword{{$current_user->id}}">Ubah Password</a>
                    <div class="dropdown-divider"></div>
                    <form method="POST" action="{{ route('logout') }}">
                        @csrf
                        <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                            this.closest('form').submit();">Log out</a>
                        </form>
                </div>
            </li>
        </ul>
        <div class="navbar-collapse">
            <div class="navbar-nav">
                <div class="logo-box"><a href="#" class="logo-text">indosat makassar</a></div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>         
    </nav>
</div>
<div class="modal fade" id="editProfile{{$current_user->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="material-icons">close</i>
                </buttn>
            </div>
            <div class="modal-body">
                    <meta name="csrf-token-editprofile" content="{{ csrf_token() }}">
                    <div class="form-group">
                        <label for="username">Username :</label>
                        @if($current_user->role == 'Admin')
                        <input type="text" class="form-control" id="current_username" value="{{$current_user->username}}" name="username" required autocomplete="off">
                        @else
                        <input type="text" class="form-control" readonly id="current_username" value="{{$current_user->username}}" name="username" required autocomplete="off">
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="name">Nama :</label>
                        <input type="text" class="form-control" id="current_name" value="{{$current_user->name}}" name="name" required autofocus autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="micro_cluster">Role :</label>
                        <input type="text" readonly class="form-control" name="current_role" id="current_role" value="{{$current_user->role}}" name="name" required autofocus autocomplete="off">
                    </div>
                    @if($current_user->role !== 'Admin')
                    <div class="form-group">
                        <label for="micro_cluster">Micro Cluster :</label>
                        <input type="text" readonly class="form-control" id="current_cluster" value="{{$current_user->micro_cluster_user}}" name="name" required autofocus autocomplete="off">
                    </div>
                    @endif
                    <input type="hidden" name="current_password" id="current_password" value="">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <button type="button" class="btn btn-primary editprofile" data-oldname="{{$current_user->name}}" data-oldusername="{{$current_user->username}}" data-oldrole="{{$current_user->role}}" data-oldpassword="{{$current_user->password}}" data-oldcluster="{{$current_user->micro_cluster_user}}" data-id="{{$current_user->id}}" data-url="{{ route('editProfile', $current_user->id) }}">Ubah</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="editPassword{{$current_user->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Ubah Password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="material-icons">close</i>
                </buttn>
            </div>
            <div class="modal-body">
                    <meta name="csrf-token-editpassword" content="{{ csrf_token() }}">
                    <div class="form-group">
                        <label for="name">Current Password :</label>
                        <input type="password" class="form-control" id="password_before" name="password_before" required autofocus autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="name">New Password :</label>
                        <input type="password" class="form-control" id="password_new" name="password_new" required autofocus autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="name">Confirm Password :</label>
                        <input type="password" class="form-control" id="password_confirm" name="password_confirm" required autofocus autocomplete="off">
                    </div>
                    <input type="hidden" name="password_check" id="password_check" value="{{$current_user->password}}">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <button type="button" class="btn btn-primary editpassword" data-id="{{$current_user->id}}" data-url="{{ route('editPassword', $current_user->id) }}">Ubah</button>
            </div>
        </div>
    </div>
</div>
@push('addon-script')
<script type="text/javascript">
$(document).ready(function() {
    $('.editprofile').click(function(e){
        e.preventDefault();
        var url = $(this).data('url');
        var id = $(this).data('id');
        var old_name = $(this).data('oldname');
        var old_username = $(this).data('oldusername');
        var old_role = $(this).data('oldrole');
        var old_password = $(this).data('oldpassword');
        var old_micro_cluster_user = $(this).data('oldcluster');
        var name = $('#current_name').val();
        var username = $('#current_username').val();
        var role = $('#current_role').val();
        var micro_cluster_user = $('#current_cluster').val();
        var password = $('#current_password').val();
        console.log(old_password);
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token-editprofile"]').attr('content')
            }
        });
        $.ajax({
            url:url,
            data:{name:name, username:username, role:role, micro_cluster_user:micro_cluster_user, password:password, id:id, old_name:old_name, old_username:old_username, old_role:old_role, old_micro_cluster_user:old_micro_cluster_user, old_password:old_password},
            method:'PUT',
            success:function(data){
                console.log(data.nothing);
                if(data.errors) {
                    var values = '';
                    $.each(data.errors, function (key, value) {
                        values = value
                    });

                Swal.fire({
                    icon: 'error',
                    title: 'Terjadi Kesalahan',
                    text: values,
                });
                }else if(data.nothing){
                    Swal.fire({
                    icon: 'warning',
                    title: 'Perhatian',
                    text: data.nothing,
                });
                    setTimeout(function(){
                    location.reload();
                    }, 1000);
                }else {
                    Swal.fire({
                    icon: 'success',
                    title: 'Berhasil',
                    text: 'Data User Berhasil Diubah!',
                });
                    setTimeout(function(){
                    location.reload();
                    }, 1000);
                }
            }
        });
    });
    $('.editpassword').click(function(e){
        e.preventDefault();
        var url = $(this).data('url');
        var id = $(this).data('id');
        var old_password = $('#password_check').val();
        var current_password = $('#password_before').val();
        var new_password = $('#password_new').val();
        var confirm_password = $('#password_confirm').val();
        console.log(old_password);
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token-editpassword"]').attr('content')
            }
        });
        $.ajax({
            url:url,
            data:{id:id, current_password:current_password, new_password:new_password, confirm_password:confirm_password, old_password:old_password},
            method:'PUT',
            success:function(data){
                console.log(data.nothing);
                if(data.errors) {
                    var values = '';
                    $.each(data.errors, function (key, value) {
                        values = value
                    });

                Swal.fire({
                    icon: 'error',
                    title: 'Terjadi Kesalahan',
                    text: values,
                });
                }else if(data.nothing){
                    Swal.fire({
                    icon: 'warning',
                    title: 'Perhatian',
                    text: data.nothing,
                });
                    setTimeout(function(){
                    location.reload();
                    }, 1000);
                }else {
                    Swal.fire({
                    icon: 'success',
                    title: 'Berhasil',
                    text: 'Data User Berhasil Diubah!',
                });
                    setTimeout(function(){
                    location.reload();
                    }, 1000);
                }
            }
        });
    });
});

</script>

@endpush

resources/views/includes/admin/script.blade.php
<!-- Javascripts -->
<script src="{{asset('admin/plugins/jquery/jquery-3.4.1.min.js')}}"></script>
<script src="{{asset('admin/plugins/bootstrap/popper.min.js')}}"></script>
<script src="{{asset('admin/plugins/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{asset('admin/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<script src="{{asset('admin/plugins/jquery-sparkline/jquery.sparkline.min.js')}}"></script>
<script src="{{asset('admin/plugins/blockui/jquery.blockUI.js')}}"></script>
<script src="{{asset('admin/plugins/flot/jquery.flot.min.js')}}"></script>
<script src="{{asset('admin/plugins/flot/jquery.flot.time.min.js')}}"></script>
<script src="{{asset('admin/plugins/flot/jquery.flot.symbol.min.js')}}"></script>
<script src="{{asset('admin/plugins/flot/jquery.flot.resize.min.js')}}"></script>
<script src="{{asset('admin/plugins/flot/jquery.flot.tooltip.min.js')}}"></script>
<script src="{{asset('admin/js/connect.min.js')}}"></script>
<script src="{{asset('admin/plugins/DataTables/datatables.min.js')}}"></script>
<script src="{{asset('admin/js/pages/datatables.js')}}"></script>
<script src="{{asset('vendor/sweetalert/sweetalert.all.js')}}"></script>

resources/views/includes/admin/sidebar.blade.php
<div class="page-sidebar">
    <div class="logo-box"><a href="#" class="logo-text">monitoring</a><a href="" id="sidebar-close"><i class="material-icons">close</i></a> <a href="#" id="sidebar-state"><i class="material-icons">adjust</i><i class="material-icons compact-sidebar-icon">panorama_fish_eye</i></a></div>
    <div class="page-sidebar-inner slimscroll">
        <ul class="accordion-menu">
            <li class="sidebar-title">
                Menu
            </li>
            <li class="{{ (request()->routeIs('/.*')) ? 'active-page' : '' }}">
                <a href="/"><i class="material-icons-outlined">dashboard</i>Dashboard</a>
            </li>
            <li class="{{ (request()->routeIs('')) || (request()->routeIs('')) ? 'active-page' : '' }}">
                <a><i class="material-icons-outlined">assignment</i>Rencana<i class="material-icons has-sub-menu">add</i></a>
                <ul class="sub-menu">
                    <li>
                        <a href="" class="{{ (request()->routeIs('')) ? 'active' : '' }}">Buat Rencana</a>
                    </li>
                    <li>
                        <a href="" class="{{ (request()->routeIs('')) ? 'active' : '' }}">Rencana Aktif</a>
                    </li>
                    <li>
                        <a href="" class="{{ (request()->routeIs('')) ? 'active' : '' }}">Rencana Selesai</a>
                    </li>
                </ul>
            </li>
            <li class="{{ (request()->routeIs('site-data.*')) || (request()->routeIs('site-transaction.*')) ? 'active-page' : '' }}">
                <a><i class="material-icons-outlined">settings_input_antenna</i>Site<i class="material-icons has-sub-menu">add</i></a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{ route('site-data.index') }}" class="{{ (request()->routeIs('site-data.index')) ? 'active' : '' }}">Data Site</a>
                    </li>
                    <li>
                        <a href="/site-transaction" class="{{ (request()->routeIs('site-data.siteTransaction')) ? 'active' : '' }}">Transaksi Site</a>
                    </li>
                </ul>
            </li>
            <li class="{{ (request()->routeIs('outlet-data.*')) ? 'active-page' : '' }}">
                <a><i class="material-icons-outlined">store</i>Outlet<i class="material-icons has-sub-menu">add</i></a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{ route('outlet-data.index') }}" class="{{ (request()->routeIs('outlet-data.index')) ? 'active' : '' }}">Data Outlet</a>
                    </li>
                    <li>
                        <a href="/outlet-transaction" class="{{ (request()->routeIs('outlet-data.outletTransaction')) ? 'active' : '' }}">Transaksi Outlet</a>
                    </li>
                </ul>
            </li>
            <li class="{{ (request()->routeIs('kpi-data.*')) ? 'active-page' : '' }}">
                <a><i class="material-icons-outlined">show_chart</i>KPI CSO<i class="material-icons has-sub-menu">add</i></a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{ route('kpi-data.index') }}" class="{{ (request()->routeIs('kpi-data.index')) ? 'active' : '' }}">Score</a>
                    </li>
                    <li>
                        <a href="/kpi-msa" class="{{ (request()->routeIs('kpi-data.msa')) ? 'active' : '' }}">MSA</a>
                    </li>
                    <li>
                        <a href="/kpi-omb" class="{{ (request()->routeIs('kpi-data.omb')) ? 'active' : '' }}">OMB</a>
                    </li>
                    <li>
                        <a href="/kpi-qsso" class="{{ (request()->routeIs('kpi-data.qsso')) ? 'active' : '' }}">QSSO</a>
                    </li>
                    <li>
                        <a href="/kpi-quro" class="{{ (request()->routeIs('kpi-data.quro')) ? 'active' : '' }}">QURO</a>
                    </li>
                    <li>
                        <a href="/kpi-sc" class="{{ (request()->routeIs('kpi-data.sc')) ? 'active' : '' }}">Serious Customer</a>
                    </li>
                    <li>
                        <a href="/kpi-ssohvc" class="{{ (request()->routeIs('kpi-data.ssohvc')) ? 'active' : '' }}">SSO HVC</a>
                    </li>
                    <li>
                        <a href="/kpi-sqsso" class="{{ (request()->routeIs('kpi-data.sqsso')) ? 'active' : '' }}">Serious QSSO</a>
                    </li>
                    <li>
                        <a href="/kpi-ssc" class="{{ (request()->routeIs('kpi-data.ssc')) ? 'active' : '' }}">Site Serious Customer</a>
                    </li>
                </ul>
            </li>
            <li class="{{ (request()->routeIs('import.*')) ? 'active-page' : '' }}">
                <a href="{{ route('import.index') }}"><i class="material-icons-outlined">cloud_upload</i>Import Data</a>
            </li>
            <li class="{{ (request()->routeIs('/.*')) ? 'active-page' : '' }}">
                <a href="profile.html"><i class="material-icons-outlined">account_circle</i>User</a>
            </li>
        </ul>
    </div>
</div>

resources/views/includes/admin/style.blade.php
<!-- Styles -->
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
<link href="{{asset('admin/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('admin/plugins/font-awesome/css/all.min.css')}}" rel="stylesheet">
<link href="{{asset('admin/plugins/DataTables/datatables.min.css')}}" rel="stylesheet">


<!-- Theme Styles -->
<link href="{{asset('admin/css/connect.min.css')}}" rel="stylesheet">
<link href="{{asset('admin/css/admin2.css')}}" rel="stylesheet">
<link href="{{asset('admin/css/dark_theme.css')}}" rel="stylesheet">
<link href="{{asset('admin/css/custom.css')}}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js')}}"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js')}}"></script>
<![endif]-->